name: WSO2 APIManager Cloud CICD
on:
  push:
    branches: [main, development, prod]

jobs:
  apim-cloud-cicd:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning repo files into VM
        uses: actions/checkout@v2.3.4

      - name: SampleStore v1.0.0 deploying to development tenant
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: mihinduranasinghe/WSO2-APIManager-Cloud-CICD-Beta@v2.0.0
        with:
          usernameTargettedTenant: "mihindu@wso2.com@development"
          passwordTargettedTenant: ${{secrets.PASSWORD}}
          APIProjectName: "SampleStore"
          APIVersion: "1.0.0"

      - name: SampleStore v2.0.0 deploying to development tenant
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: mihinduranasinghe/WSO2-APIManager-Cloud-CICD-Beta@v2.0.0
        with:
          usernameTargettedTenant: "mihindu@wso2.com@development"
          passwordTargettedTenant: ${{secrets.PASSWORD}}
          APIProjectName: "SampleStore"
          APIVersion: "2.0.0"

      - name: SampleStore v1.0.0 deploying to production tenant
        if: github.event_name == 'push' && github.ref == 'refs/heads/prod'
        uses: mihinduranasinghe/WSO2-APIManager-Cloud-CICD-Beta@v2.0.0
        with:
          usernameTargettedTenant: "mihindu@wso2.com@production"
          passwordTargettedTenant: ${{secrets.PASSWORD}}
          APIProjectName: "SampleStore"
          APIVersion: "1.0.0"

      - name: SampleStore v2.0.0 deploying to production tenant
        if: github.event_name == 'push' && github.ref == 'refs/heads/prod'
        uses: mihinduranasinghe/WSO2-APIManager-Cloud-CICD-Beta@v2.0.0
        with:
          usernameTargettedTenant: "mihindu@wso2.com@production"
          passwordTargettedTenant: ${{secrets.PASSWORD}}
          APIProjectName: "SampleStore"
          APIVersion: "2.0.0"
